### 1. Realizar login para obter o token
# @name loginRequest
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "cleberson@example.com",
  "password": "cleberson123"
}

### 2. Tentar deletar um usuário sem token (deve falhar)
DELETE http://localhost:3000/users/1

### 3. Tentar deletar um usuário com token
# A variável {{loginRequest.response.body.token}} pega o token da resposta da requisição de login.
DELETE http://localhost:3000/users/1
Authorization: Bearer {{loginRequest.response.body.token}}