# Variáveis do ambiente
@baseUrl = http://localhost:3000
@email = teste_{{$randomInt}}@teste.com
@password = 123456
@token =

###
# 1. Criar um novo usuário para o teste
# @name newUserRequest
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "name": "Usuario de Teste",
  "login": "{{email}}",
  "password": "{{password}}"
}

###
# 2. Fazer login para obter o token JWT
# O token da resposta será salvo na variável @token
# @name loginRequest
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "login": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("token", response.body.token);
%}

###
# 3. Testar Rota Protegida - COM TOKEN (Deve funcionar)
GET {{baseUrl}}/api/users
Authorization: Bearer {{token}}


###
# 4. Testar Rota Protegida - SEM TOKEN (Deve falhar)
GET {{baseUrl}}/api/users