### 1. Criar um novo usuário (para ter com o que logar)
# @name createUserRequest
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Cleberson Eugenio",
  "email": "cleberson@example.com",
  "password": "cleberson123",
  "isActive": true,
  "cellphone": "11988079168"
}

### SEPARADOR OBRIGATÓRIO ###

### 2. Fazer login para obter o token
# @name loginRequest
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "cleberson@example.com",
  "password": "cleberson123"
}

### SEPARADOR OBRIGATÓRIO ###

### 3. Listar todos os usuários (Rota Protegida)
GET http://localhost:3000/users
Authorization: Bearer {{loginRequest.response.body.token}}

### SEPARADOR OBRIGATÓRIO ###

### 4. Buscar um usuário pelo ID (Rota Protegida)
# IMPORTANTE: Substitua o "1" abaixo pelo ID do usuário que você quer testar.
# Você pode encontrar o ID no seu banco de dados (via phpMyAdmin, DBeaver, etc.)
# depois de criá-lo com a requisição #1.
GET http://localhost:3000/users/3
Authorization: Bearer {{loginRequest.response.body.token}}

### SEPARADOR OBRIGATÓRIO ###

### 5. Atualizar o nome do usuário (Rota Protegida)
# IMPORTANTE: Substitua o "1" abaixo pelo ID do usuário.
PUT http://localhost:3000/users/3
Content-Type: application/json
Authorization: Bearer {{loginRequest.response.body.token}}

{
  "name": "Cleberson Junior"
}

### SEPARADOR OBRIGATÓRIO ###

### 6. Deletar o usuário (Rota Protegida)
# IMPORTANTE: Substitua o "1" abaixo pelo ID do usuário.
DELETE http://localhost:3000/users/3
Authorization: Bearer {{loginRequest.response.body.token}}  